# Generated by Django 4.0.1 on 2022-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
