# Generated by Django 4.0.1 on 2022-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='link',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время и Дата опубликования'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
